apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-mysql-persistent-storage
  labels:
    app: wordpress
    tier: mysql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/jenkins/wp-data-files/mysql"
