apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-mysql-persistent-storage
  labels:
    app: wordpress
spec:
  accessModes:
#    - ReadWriteMany
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
